// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jwt_rest_api.Data;

#nullable disable

namespace jwt_rest_api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("jwt_rest_api.Models.EventData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArcName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventDataMaster");
                });

            modelBuilder.Entity("jwt_rest_api.Models.EventEncounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("EncounterDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EncounterEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncounterObject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EncounterStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventEncounters");
                });

            modelBuilder.Entity("jwt_rest_api.Models.GameProgress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("InventoryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("StateDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId");

                    b.ToTable("GameProgresses");
                });

            modelBuilder.Entity("jwt_rest_api.Models.GameSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("SessionDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SessionIsFinished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SessionStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("jwt_rest_api.Models.NpcInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PsychoImpact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NpcInteractions");
                });

            modelBuilder.Entity("jwt_rest_api.Models.PlayerResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.ToTable("PlayerResponses");
                });

            modelBuilder.Entity("jwt_rest_api.Models.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SessionEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("EventDataId")
                        .HasColumnType("integer");

                    b.Property<int>("EventDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EventStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventDataId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SessionMinigame", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinigameDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MinigameEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinigameIsRelatedWithEncounterId")
                        .HasColumnType("text");

                    b.Property<DateTime>("MinigameStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("SessionMinigames");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SubEventData", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EncounterId"));

                    b.Property<string>("EncounterDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EncounterValue")
                        .HasColumnType("boolean");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.HasKey("EncounterId");

                    b.HasIndex("EventId");

                    b.ToTable("SubEventDataMaster");
                });

            modelBuilder.Entity("jwt_rest_api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleSubjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPlayedSessionId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("jwt_rest_api.Models.EventEncounter", b =>
                {
                    b.HasOne("jwt_rest_api.Models.SessionEvent", "SessionEvent")
                        .WithMany("Encounters")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionEvent");
                });

            modelBuilder.Entity("jwt_rest_api.Models.GameProgress", b =>
                {
                    b.HasOne("jwt_rest_api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("jwt_rest_api.Models.GameProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("jwt_rest_api.Models.GameSession", b =>
                {
                    b.HasOne("jwt_rest_api.Models.User", "User")
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("jwt_rest_api.Models.NpcInteraction", b =>
                {
                    b.HasOne("jwt_rest_api.Models.User", "User")
                        .WithMany("NpcInteractions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("jwt_rest_api.Models.PlayerResponse", b =>
                {
                    b.HasOne("jwt_rest_api.Models.EventEncounter", "Encounter")
                        .WithMany("PlayerResponses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SessionEvent", b =>
                {
                    b.HasOne("jwt_rest_api.Models.EventData", "EventData")
                        .WithMany()
                        .HasForeignKey("EventDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("jwt_rest_api.Models.GameSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventData");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SessionMinigame", b =>
                {
                    b.HasOne("jwt_rest_api.Models.SessionEvent", "SessionEvent")
                        .WithMany("Minigames")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionEvent");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SubEventData", b =>
                {
                    b.HasOne("jwt_rest_api.Models.EventData", "EventData")
                        .WithMany("SubEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventData");
                });

            modelBuilder.Entity("jwt_rest_api.Models.EventData", b =>
                {
                    b.Navigation("SubEvents");
                });

            modelBuilder.Entity("jwt_rest_api.Models.EventEncounter", b =>
                {
                    b.Navigation("PlayerResponses");
                });

            modelBuilder.Entity("jwt_rest_api.Models.GameSession", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("jwt_rest_api.Models.SessionEvent", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Minigames");
                });

            modelBuilder.Entity("jwt_rest_api.Models.User", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("NpcInteractions");
                });
#pragma warning restore 612, 618
        }
    }
}
